window.COVERAGEFIT_CONFIG={
 slug:'business',storageKey:'coveragefit_business_report',profileStorageKey:'coveragefit_business_profile',reportPath:'/business/report/',defaultName:'Business owner',detailKey:'businessZip',subjectLabel:'CoverageFit Business',finalButtonLabel:'Build My Business Coverage Review',warningPoint:-10,
 chapterLabels:{Operations:'Your Operations',Liability:'Liability & Contracts',Property:'Property & Income',People:'Employees & Workforce',Vehicles:'Business Driving',Professional:'Professional Risk',Cyber:'Data & Technology',Continuity:'Business Continuity'},
 earlyInsight:{concernTitle:'Your business may already have a protection gap worth reviewing.',concernCopy:'Changes in operations and liability exposures are easy to miss as a business grows. We will carry this context into your Business Protection Snapshot.',strongTitle:'You have a useful business protection foundation.',strongCopy:'Your first answers suggest you have already thought about important operational risks. We will help you confirm what is strong and what still deserves attention.'},
 resultCopy:'Your responses revealed positive starting points and a few business risks worth confirming with a licensed insurance professional.',strongResultCopy:'Your responses suggest a strong starting point. A focused Business Protection Review can confirm that your insurance still fits your operations.',defaultPriority:'Confirm that your current insurance accurately reflects how your business operates today.',
 questions:[
 {key:'operations',category:'Operations',weight:14,title:'Have your services, products, locations, customers, or business activities changed since your insurance was last reviewed?',help:'Why we are asking: policies are written around the operations described to the insurer. Growth or new activities can create gaps if the policy was never updated.',answers:[
 {label:'No material changes',sub:'My current policy was reviewed after our latest changes.',points:0,tag:'Business Operations',insight:'Your current insurance appears to reflect your present operations.',question:'Does the policy description accurately include every service, product, and location we currently use?'},
 {label:'Some changes',sub:'We have grown or adjusted operations since the last review.',points:-10,tag:'Business Operations',insight:'Your business operations may have changed since the policy was last reviewed.',question:'Which recent changes should be added to or discussed with the insurer?'},
 {label:'Not sure',sub:'I do not know what operations the policy describes.',points:-15,tag:'Business Operations',insight:'You are unsure whether the policy accurately describes your current operations.',question:'What business activities and classifications are currently listed on my policy?'}]},
 {key:'liability',category:'Liability',weight:14,title:'If a customer or member of the public were seriously injured because of your business, how confident are you in your liability protection?',help:'Why we are asking: a serious injury can create legal defense costs, settlements, and reputational strain.',answers:[
 {label:'Very confident',sub:'I know my limits and major exclusions.',points:0,tag:'General Liability',insight:'You understand your main general liability protection.',question:'Do my limits and exclusions still fit the size and nature of my business?'},
 {label:'Somewhat confident',sub:'I have coverage but have not reviewed the details recently.',points:-8,tag:'General Liability',insight:'Your general liability limits and terms may deserve a fresh review.',question:'What claims, locations, and operations does my liability policy cover or exclude?'},
 {label:'Not sure or uninsured',sub:'I do not know my limits or may not have coverage.',points:-18,tag:'General Liability',insight:'Your business liability protection is unclear or may be missing.',question:'What liability protection should be evaluated for my current operations?'}]},
 {key:'property',category:'Property',weight:10,title:'If your equipment, inventory, furniture, or improvements were damaged or stolen, could your current limits replace them today?',help:'Why we are asking: business property values change as companies add equipment, inventory, and tenant improvements.',answers:[
 {label:'Yes',sub:'Values were reviewed recently.',points:0,tag:'Business Property',insight:'Your business property values were reviewed recently.',question:'Are replacement cost, special limits, and property away from the premises handled appropriately?'},
 {label:'Possibly',sub:'We have added property since the last review.',points:-8,tag:'Business Property',insight:'Your business property limits may not reflect recent purchases or growth.',question:'Can we update the values for equipment, inventory, and tenant improvements?'},
 {label:'Not sure',sub:'I do not know the limit or settlement method.',points:-14,tag:'Business Property',insight:'Your business property limit and settlement method are unclear.',question:'What property limit and valuation method does my current policy use?'}]},
 {key:'income',category:'Property',weight:14,title:'If a covered loss forced your business to close temporarily, how long could it keep paying rent, payroll, loans, and other ongoing expenses?',help:'Why we are asking: property coverage repairs physical damage, but business income protection may help the company survive the interruption.',answers:[
 {label:'Six months or longer',sub:'We have coverage or reserves designed for an extended interruption.',points:0,tag:'Business Income',insight:'You have considered how the business would fund an extended shutdown.',question:'How is my business income limit calculated, and what waiting period applies?'},
 {label:'A few weeks or months',sub:'A longer shutdown would create strain.',points:-10,tag:'Business Income',insight:'An extended shutdown could create meaningful financial strain.',question:'How long would my current business income protection support ongoing expenses?'},
 {label:'Very little or not sure',sub:'A shutdown could quickly threaten the business.',points:-18,tag:'Business Income',insight:'Your business may be financially vulnerable to an extended covered shutdown.',question:'What business income and extra expense protection should be evaluated?'}]},
 {key:'workers',category:'People',weight:12,title:'Does anyone perform work for your business, including employees, part-time workers, subcontractors, or unpaid helpers?',help:'Why we are asking: worker classifications and state requirements can create serious exposure when they are misunderstood.',answers:[
 {label:'Yes, and coverage is reviewed',sub:'We understand our payroll, classifications, and workers compensation setup.',points:0,tag:'Workers Compensation',insight:'You have reviewed your workforce and workers compensation setup.',question:'Are every worker and payroll classification accurately reflected?'},
 {label:'Yes, but I am unsure',sub:'We use employees, contractors, or helpers and have questions.',points:-14,tag:'Workers Compensation',insight:'Your worker classifications or workers compensation setup may need review.',question:'Could any contractors or helpers legally be treated as employees, and are all classifications accurate?'},
 {label:'No workers',sub:'Only the owner currently performs work.',points:0,tag:'Workers Compensation',insight:'You indicated that only the owner currently performs work.',question:'Would future hiring or use of contractors trigger workers compensation requirements?'}]},
 {key:'vehicles',category:'Vehicles',weight:12,title:'Are personal, employee-owned, rented, or company-owned vehicles ever used for business purposes?',help:'Why we are asking: personal auto policies may not fully respond to business use, and businesses can face liability from employee driving.',answers:[
 {label:'Yes, and it is insured for business use',sub:'We have reviewed owned and non-owned vehicle exposures.',points:0,tag:'Business Auto',insight:'You have reviewed vehicles used for business purposes.',question:'Do owned, hired, and non-owned vehicle exposures all have appropriate protection?'},
 {label:'Yes, but only personal policies are used',sub:'Owners or employees use personal vehicles for work.',points:-16,tag:'Business Auto',insight:'Personal or employee-owned vehicles may be creating an uninsured business exposure.',question:'How would the business be protected if an employee caused a serious accident while driving for work?'},
 {label:'No business driving',sub:'Vehicles are not used in the operation.',points:0,tag:'Business Auto',insight:'You indicated that vehicles are not used for business purposes.',question:'Are deliveries, errands, client visits, or occasional rentals truly excluded from our operations?'}]},
 {key:'professional',category:'Professional',weight:10,title:'Could a customer claim that your advice, work, design, recommendation, or professional service caused a financial loss?',help:'Why we are asking: general liability often focuses on bodily injury and property damage, not purely financial harm caused by professional services.',answers:[
 {label:'Yes, and professional coverage is in place',sub:'We have reviewed errors and omissions or professional liability.',points:0,tag:'Professional Liability',insight:'You have considered claims arising from professional services.',question:'Does the professional liability policy match every service we provide?'},
 {label:'Yes, but I only have general liability',sub:'A client could allege an error or failure in our work.',points:-16,tag:'Professional Liability',insight:'Your professional services may create exposure not addressed by general liability alone.',question:'Should professional liability or errors and omissions coverage be evaluated?'},
 {label:'No or unlikely',sub:'We do not provide advice or professional services.',points:0,tag:'Professional Liability',insight:'You do not believe your operations create a material professional liability exposure.',question:'Could any promise, design, consultation, or service failure still create a financial-loss claim?'}]},
 {key:'cyber',category:'Cyber',weight:10,title:'Does your business collect, store, process, or transmit customer, employee, payment, health, or other sensitive information?',help:'Why we are asking: even small businesses can face notification costs, fraud, ransomware, and liability after a data incident.',answers:[
 {label:'Yes, and cyber protection is reviewed',sub:'We have security controls and cyber insurance.',points:0,tag:'Cyber Liability',insight:'You have considered data and cyber exposures.',question:'Do our cyber limits, controls, and incident-response resources still match our systems?'},
 {label:'Yes, but no dedicated cyber policy',sub:'We store or process sensitive information without separate coverage.',points:-14,tag:'Cyber Liability',insight:'Your business handles sensitive information without confirmed cyber protection.',question:'What expenses and liabilities would we face after a breach or ransomware event?'},
 {label:'Very little or none',sub:'We retain minimal sensitive information.',points:0,tag:'Cyber Liability',insight:'You indicated that the business retains little sensitive information.',question:'Do email, cloud services, payment systems, or employee records still create cyber exposure?'}]},
 {key:'contracts',category:'Liability',weight:10,title:'Do customers, landlords, schools, vendors, or other organizations require certificates, additional insured status, or specific limits?',help:'Why we are asking: contracts can require broader limits or endorsements than a basic policy automatically provides.',answers:[
 {label:'Yes, and requirements are reviewed before signing',sub:'We coordinate contracts and certificates with our insurance professional.',points:0,tag:'Contract Requirements',insight:'You review contractual insurance requirements before committing.',question:'Are all required limits, additional insured endorsements, and waivers actually available under my policy?'},
 {label:'Yes, but usually after signing',sub:'We often discover requirements when a certificate is requested.',points:-12,tag:'Contract Requirements',insight:'Contract requirements may be reviewed too late to confirm compliance.',question:'Can we review current contracts before promising coverage or endorsements?'},
 {label:'No or not sure',sub:'I do not know whether our agreements contain insurance requirements.',points:-6,tag:'Contract Requirements',insight:'You may not have reviewed agreements for insurance obligations.',question:'Which leases or customer agreements contain insurance and indemnity requirements?'}]},
 {key:'umbrella',category:'Liability',weight:8,title:'If a severe claim exceeded your primary policy limits, does the business have an additional layer of liability protection?',help:'Why we are asking: a large injury, auto accident, or lawsuit can exceed the limits of an underlying policy.',answers:[
 {label:'Yes',sub:'The business has umbrella or excess liability coverage.',points:0,tag:'Umbrella or Excess',insight:'Your business has an additional layer of liability protection.',question:'Which underlying policies are covered by the umbrella, and are the limits adequate?'},
 {label:'No',sub:'We only carry the primary policy limits.',points:-10,tag:'Umbrella or Excess',insight:'A severe claim may be limited to your primary policy limits.',question:'Would umbrella or excess liability materially strengthen our protection?'},
 {label:'Not sure',sub:'I do not know whether additional limits apply.',points:-8,tag:'Umbrella or Excess',insight:'You have not confirmed whether umbrella or excess liability applies.',question:'Do we currently have excess limits, and which policies sit underneath them?'}]},
 {key:'continuity',category:'Continuity',weight:10,title:'If an owner or key employee died or became unable to work, does the business have a written and funded continuation plan?',help:'Why we are asking: operations, ownership, loans, and family income can all be disrupted when a key person is suddenly unavailable.',answers:[
 {label:'Yes',sub:'We have documented and funded plans.',points:0,tag:'Business Continuity',insight:'You have considered ownership and key-person continuity.',question:'Are the buy-sell, key-person, and succession arrangements still properly funded and current?'},
 {label:'Partially',sub:'We have discussed it but the plan is incomplete or unfunded.',points:-10,tag:'Business Continuity',insight:'Your business continuation plan may be incomplete or unfunded.',question:'What would happen to ownership, debt, payroll, and family income if a key person were lost?'},
 {label:'No',sub:'There is no formal plan.',points:-14,tag:'Business Continuity',insight:'The business does not have a formal plan for the loss of an owner or key employee.',question:'What succession, key-person, or buy-sell planning should be evaluated?'}]}
 ]
};
