const path=require('path');
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const store=new Map();
const storage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const window={dispatchEvent(){},addEventListener(){}};
const context={window,localStorage:storage,sessionStorage:storage,CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},crypto:{randomUUID:()=> 'test-session-id'},console,setTimeout,clearTimeout,Date,Math};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'assets/js/property-intelligence.js'),'utf8'),context);
const pi=window.CoverageFitPropertyIntelligence;
assert(pi);
const address=pi.normalizeAddress({line1:' 123 Main St ',city:'San Jose',state:'ca',zip:'95112'});
assert.equal(address.state,'CA');assert.equal(address.postalCode,'95112');assert(address.isComplete);
let profile=pi.createProfile({address,raw:{yearBuilt:'1998',squareFeet:'2,184',stories:2,pool:false},provider:{id:'fixture',name:'Fixture',defaultConfidence:.8}});
assert.equal(profile.data.squareFeet,2184);assert(profile.quality.confidence>0);assert(profile.quality.completeness>0);
profile=pi.mergeProfile(profile,{roofYear:2021},{verifiedByUser:true});
assert.equal(profile.data.roofYear,2021);assert.equal(profile.fieldMeta.roofYear.confidence,1);assert(profile.fieldMeta.roofYear.verifiedByUser);
pi.save(profile);assert.equal(pi.load().data.roofYear,2021);
pi.registerProvider({id:'test-provider',name:'Test',defaultConfidence:.9,async lookup(addr){return{address:addr,data:{yearBuilt:2005,squareFeet:1900,stories:1}}}});
(async()=>{const service=new pi.PropertyIntelligenceService({registry:pi.registry,cache:new pi.PropertyCache({storage:null}),providerOrder:['test-provider']});const result=await service.lookup(address,{forceRefresh:true});assert.equal(result.provider.id,'test-provider');assert.equal(result.data.yearBuilt,2005);const manual=await service.lookup({},{});assert.equal(manual.status,'manual_required');console.log('B4A QA: 14 assertions passed');})().catch(e=>{console.error(e);process.exit(1)});
