const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = __dirname;
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const exists = rel => fs.existsSync(path.join(root, rel));
const hash = rel => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, rel))).digest('hex');
const checks=[]; const check=(n,c)=>{assert.ok(c,n);checks.push(n)};
const version=read('VERSION').trim(); const pkg=JSON.parse(read('package.json'));
const api=require('./assets/js/advisory-progressive-discovery-branching.js');
const contract=JSON.parse(read('CF_ADV_1_9_BRANCHING_CONTRACT.json'));
const html=read('assessment/index.html');
const relationship=read('assets/js/advisory-relationship-discovery.js');
const lifestyle=read('assets/js/advisory-lifestyle-discovery.js');
const branchText=read('assets/js/advisory-progressive-discovery-branching.js');
const css=read('assets/css/advisory-progressive-branching.css');
check('release remains compatible after 3.20.80', ['3.20.80','3.20.81','3.20.82','3.20.83'].includes(version) && pkg.version===version);
check('package remains compatible after progressive branching', /Progressive Discovery Branching|Customer Language & Reaction Layer|Your CoverageFit Results Model|Why This Fits You Recommendation Cards/i.test(pkg.description));
check('runtime exists', exists('assets/js/advisory-progressive-discovery-branching.js'));
check('stylesheet exists', exists('assets/css/advisory-progressive-branching.css'));
check('contract exists', exists('CF_ADV_1_9_BRANCHING_CONTRACT.json'));
check('sprint doc exists', exists('SPRINT-CF-ADV-1.9.md'));
check('runtime identity stable', api.BUILD==='CF-ADV-1.9' && api.VERSION==='1.0.0');
check('runtime contract matches JSON', api.CONTRACT_ID===contract.id);
check('one follow-up boundary explicit', api.boundaries.oneFollowUpAtATime===true && contract.boundaries.one_follow_up_at_a_time===true);
check('branch durability explicit', api.boundaries.branchStateDurable===true && contract.boundaries.branch_state_durable===true);
check('score boundary explicit', api.boundaries.scoreFormulaChanged===false && contract.boundaries.score_formula_changed===false);
check('recommendation eligibility protected', api.boundaries.recommendationEligibilityChanged===false && contract.boundaries.recommendation_eligibility_changed===false);
let b=api.relationship({tenure:{key:'3_5'},likes:[{key:'service'}],mustKeep:[]});
check('preserve branch defaults suppressed for short tenure', b.active===false);
b=api.relationship({tenure:{key:'10_plus'},likes:[{key:'price'}],mustKeep:[]});
check('tenure alone does not trigger preserve branch', b.active===false);
b=api.relationship({tenure:{key:'10_plus'},likes:[{key:'service'}],mustKeep:[]});
check('10 plus and explicit service trigger preserve branch', b.active===true && b.trigger==='10_plus_tenure_and_service');
check('preserve branch cites only explicit source facts', b.sourceFacts.join('|')==='currentCarrierTenure|currentCarrierLikes.service');
check('preserve prompt is neutral', /make sure not to lose/i.test(b.prompt) && !/need|must buy|lawsuit/i.test(b.prompt));
b=api.relationship({tenure:{key:'1_2'},likes:[{key:'price'}],mustKeep:[{key:'coverage'}],preserveLegacyMustKeep:true});
check('restored preserve answer remains visible', b.active===true && b.previouslyAnswered===true && b.legacyPreserved===true && b.trigger==='restored_legacy_answer');
let l=api.lifestyle({primaryHome:{key:'not_primary'},stayIntent:{key:'5_plus'},improvements:null});
check('non-primary home suppresses improvements follow-up', l.active===false);
l=api.lifestyle({primaryHome:{key:'primary_residence'},stayIntent:{key:'2_5'},improvements:null});
check('shorter stay suppresses improvements follow-up', l.active===false);
l=api.lifestyle({primaryHome:{key:'primary_residence'},stayIntent:{key:'5_plus'},improvements:null});
check('primary plus long term triggers improvements follow-up', l.active===true && l.trigger==='primary_residence_and_5_plus_stay');
check('improvements branch cites explicit source facts', l.sourceFacts.join('|')==='homeOwnership|stayIntent');
check('improvements prompt is neutral', /one extra detail may help/i.test(l.prompt) && !/underinsured|risk|loss/i.test(l.prompt));
l=api.lifestyle({primaryHome:{key:'not_primary'},stayIntent:{key:'2_5'},improvements:{key:'some',label:'Some updates'},preserveLegacyImprovements:true});
check('restored improvements answer remains visible', l.active===true && l.previouslyAnswered===true && l.legacyPreserved===true && l.trigger==='restored_legacy_answer');

check('new preserve answer does not keep branch alive after trigger facts change', api.relationship({tenure:{key:'1_2'},likes:[{key:'price'}],mustKeep:[{key:'coverage'}]}).active===false);
check('new improvements answer does not keep branch alive after trigger facts change', api.lifestyle({primaryHome:{key:'not_primary'},stayIntent:{key:'2_5'},improvements:{key:'some',label:'Some updates'}}).active===false);
const next=api.nextFollowUp({relationship:{tenure:{key:'10_plus'},likes:[{key:'service'}],mustKeep:[]},lifestyle:{primaryHome:{key:'primary_residence'},stayIntent:{key:'5_plus'},improvements:null}});
check('only first eligible follow-up is returned at a time', next && next.id==='preserve-what-works');
const suppressed=api.knownFactSuppression({reviewReasonInherited:true,currentCarrierInherited:true,currentCarrierTenureKnown:true});
check('known facts expose zero-repeat suppression map', suppressed.reviewReason && suppressed.currentCarrier && suppressed.currentCarrierTenure);
check('relationship UI has hidden bounded preserve fieldset', html.includes('id="advisoryMustKeepFieldset" hidden'));
check('relationship UI has follow-up cue', html.includes('id="advisoryRelationshipPreserveCue"'));
check('lifestyle UI has hidden improvements fieldset', html.includes('id="advisoryImprovementsFieldset" hidden'));
check('lifestyle UI has follow-up cue', html.includes('id="advisoryLifestyleImprovementsCue"'));
check('runtime loads before relationship discovery', html.indexOf('advisory-progressive-discovery-branching.js') < html.indexOf('advisory-relationship-discovery.js'));
check('runtime loads before lifestyle discovery', html.indexOf('advisory-progressive-discovery-branching.js') < html.indexOf('advisory-lifestyle-discovery.js'));
check('branch CSS loads', html.includes('/assets/css/advisory-progressive-branching.css'));
check('relationship consumes progressive engine', relationship.includes('CoverageFitAdvisoryProgressiveDiscoveryBranching'));
check('relationship completion gates mustKeep only when branch active', relationship.includes('(preserveBranch.active && !listReady(state.mustKeep))'));
check('relationship continuation gates mustKeep conditionally', relationship.includes('(!branch.active || listReady(state.mustKeep))'));
check('relationship branch state persists', relationship.includes('branchState: clone(state.branchState'));
check('relationship clears hidden stale branch evidence', relationship.includes('if (!branch.active && state.mustKeep.length) state.mustKeep = []'));
check('lifestyle consumes progressive engine', lifestyle.includes('CoverageFitAdvisoryProgressiveDiscoveryBranching'));
check('lifestyle completion gates improvements conditionally', lifestyle.includes('(!improvementsBranch.active || hasRecord(state.improvements))'));
check('lifestyle continuation gates improvements conditionally', lifestyle.includes('(!improvementsBranch.active || hasRecord(state.improvements))'));
check('lifestyle branch state persists', lifestyle.includes('branchState: clone(state.branchState'));
check('lifestyle clears hidden stale branch evidence', lifestyle.includes('if (!branch.active && state.improvements) state.improvements = null'));
check('branching runtime does not import scoring', !/ProtectionScore|protection-score|scoreEvaluation/.test(branchText));
check('branching runtime does not import recommendation engine', !/RecommendationEngine|recommendation-engine/.test(branchText));
check('branching runtime does not create customer signals', !/customerSignals/.test(branchText));
check('branching runtime does not create recommendation anchors', !/recommendationAnchors/.test(branchText));
check('CSS hides inactive cues', css.includes('.advisory-branch-followup[hidden]{display:none}'));
check('CSS supports reduced motion', css.includes('prefers-reduced-motion'));
check('Protection Score remains byte-certified', hash('assets/js/protection-score.js')==='0cf3190a5bb99aceb0e527f91268247481fd14e67acd81fb35db3accd8a5f2a8');
check('Home recommendation rules remain byte-certified', hash('assets/js/home-recommendation-rules.js')==='0c4fb83590a2d0f29803f593a6716ba961c49a651542b74d53e01b9e33df4629');
check('recommendation engine remains byte-certified', hash('assets/js/recommendation-engine.js')==='0d5973be5455d416c8f2477ce08f327adff0fff91bdb987efe62c6e8e8e6fe18');
check('legacy Workspace remains byte-certified', hash('assets/js/workspace-data.js')==='8a11fd11fb3e027cfef746f4f9214b9d345c5db49862921dff27bbcfcc49eef2');
check('contract says scored question catalog unchanged', contract.boundaries.scored_question_catalog_changed===false);
check('contract says signal rules unchanged', contract.boundaries.signal_rules_changed===false);
check('contract says branch answer is not consent', contract.boundaries.branch_answer_is_consent===false);
check('roadmap marks 1.9 complete', read('CF-ADV-ROADMAP.md').includes('CF-ADV-1.9 implementation status — COMPLETE in v3.20.80'));
check('roadmap preserves 1.10 progression after 1.9', read('CF-ADV-ROADMAP.md').includes('## CF-ADV-1.10 — Customer Language & Reaction Layer'));
check('roadmap can advance beyond 1.10', read('CF-ADV-ROADMAP.md').includes('Next: `CF-ADV-1.11 — “Your CoverageFit” Results Model`'));
console.log(`CF-ADV-1.9 QA: ${checks.length}/${checks.length} passed`);
