import assert from 'node:assert/strict';
import {normalizeOutreachRecord,coverageFitOutreachUrl,fallbackOutreachAnalysis,handleOutreachOpportunities,analyzeOutreachOpportunity} from './server/displacement-outreach-core.mjs';

class Store{constructor(){this.m=new Map()}async get(k){return this.m.get(k)||null}async setJSON(k,v){this.m.set(k,JSON.parse(JSON.stringify(v)))}async list({prefix=''}){return{blobs:[...this.m.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}}
const TOKEN='producer-access-key-1234567890-abcdef';
const env={COVERAGEFIT_PRODUCER_ACCESS_TOKEN:TOKEN};
const req=(url,method='GET',body=null,token=TOKEN)=>new Request(url,{method,headers:{Authorization:`Bearer ${token}`,Origin:'https://coveragefit.com',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
let pass=0;const test=async(name,fn)=>{await fn();pass++;console.log('PASS',name)};
await test('normalizes safe opportunity',()=>{const r=normalizeOutreachRecord({channel:'reddit',sourceUrl:'javascript:alert(1)',sourceContext:'Safeco nonrenewal condo California'});assert.equal(r.sourceUrl,'');assert.equal(r.privacy.autoPosting,false);assert.match(r.id,/^opp_/)});
await test('attribution URL stays opaque and source tagged',()=>{const u=coverageFitOutreachUrl({id:'opp_12345678',channel:'reddit',kind:'discussion',carrier:'safeco'});assert.match(u,/\/nonrenewal\/safeco\//);assert.match(u,/utm_source=reddit/);assert.doesNotMatch(u,/name=|email=|phone=/)});
await test('high intent fallback responds',()=>{const a=fallbackOutreachAnalysis({channel:'reddit',kind:'discussion',location:'San Jose, CA',sourceContext:'Safeco sent a nonrenewal on our condo. Policy ends next month. Anyone know who is writing condos?'});assert.ok(a.relevanceScore>=65);assert.equal(a.recommendation,'respond');assert.equal(a.carrier,'safeco');assert.equal(a.propertyType,'condo');assert.ok(a.drafts.firstReply);assert.doesNotMatch(a.drafts.firstReply,/coveragefit\.com/)});
await test('customer service noise is suppressed',()=>{const a=fallbackOutreachAnalysis({channel:'reddit',sourceContext:'Safeco customer service login pay bill phone number'});assert.equal(a.recommendation,'skip')});
await test('relationship drafts include pass-along resource token',()=>{const a=fallbackOutreachAnalysis({kind:'relationship',channel:'hoa',sourceContext:'Condo HOA community in California'});assert.ok(a.drafts.emailBody.includes('{coveragefit_url}'));assert.ok(a.relevanceScore>=60)});
await test('API requires producer auth',async()=>{const r=await handleOutreachOpportunities(req('https://coveragefit.com/api/outreach/opportunities','GET',null,'wrong-token-xxxxxxxxxxxxxxxxxxxx'),{env,store:new Store()});assert.equal(r.status,401)});
await test('API create/list/update lifecycle',async()=>{const store=new Store();let r=await handleOutreachOpportunities(req('https://coveragefit.com/api/outreach/opportunities','POST',{record:{channel:'nextdoor',sourceContext:'Home insurance nonrenewal California'}}),{env,store});assert.equal(r.status,201);let b=await r.json();const id=b.record.id;r=await handleOutreachOpportunities(req('https://coveragefit.com/api/outreach/opportunities'),{env,store});b=await r.json();assert.equal(b.count,1);r=await handleOutreachOpportunities(req('https://coveragefit.com/api/outreach/opportunities','PATCH',{id,action:'set_status',status:'responded'}),{env,store});b=await r.json();assert.equal(b.record.status,'responded');assert.ok(b.record.lastRespondedAt)});
await test('AI endpoint uses deterministic fallback without API key',async()=>{const r=await analyzeOutreachOpportunity(req('https://coveragefit.com/api/outreach/ai','POST',{record:{channel:'facebook',sourceContext:'Safeco nonrenewed our condo in California'}}),{env});const b=await r.json();assert.equal(r.status,200);assert.equal(b.aiConfigured,false);assert.equal(b.analysis.provider,'fallback')});
await test('configured AI path sends store:false and parses structured output',async()=>{const originalFetch=globalThis.fetch;let seen=null;globalThis.fetch=async(url,options)=>{seen=JSON.parse(options.body);return Response.json({output:[{content:[{text:JSON.stringify({relevanceScore:88,recommendation:'respond',analysisSummary:'Clear nonrenewal.',reasoning:'Explicit displacement request.',carrier:'safeco',propertyType:'condo',tags:['displacement'],drafts:{firstReply:'Helpful reply',followUp:'Follow {coveragefit_url}',emailSubject:'',emailBody:'',sms:''}})}]}]})};try{const r=await analyzeOutreachOpportunity(req('https://coveragefit.com/api/outreach/ai','POST',{record:{channel:'reddit',sourceContext:'Safeco nonrenewal condo'}}),{env:{...env,OPENAI_API_KEY:'sk-test-key',COVERAGEFIT_OUTREACH_AI_MODEL:'gpt-5.6-luna'}});const b=await r.json();assert.equal(b.analysis.provider,'openai');assert.equal(b.analysis.relevanceScore,88);assert.equal(seen.store,false);assert.equal(seen.model,'gpt-5.6-luna');assert.equal(seen.store,false);assert.equal(seen.reasoning.effort,'low');assert.equal(seen.max_output_tokens,900);assert.equal(seen.text.verbosity,'low');assert.equal(seen.text.format.type,'json_schema')}finally{globalThis.fetch=originalFetch}});
await test('AI endpoint rejects cross-origin writes',async()=>{const request=new Request('https://coveragefit.com/api/outreach/ai',{method:'POST',headers:{Authorization:`Bearer ${TOKEN}`,Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'});const r=await analyzeOutreachOpportunity(request,{env});assert.equal(r.status,403)});
console.log(`\n${pass}/10 outreach QA checks passed`);
