const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const root = __dirname;
const html = fs.readFileSync(root + '/agent/workspace/index.html','utf8');
const app = fs.readFileSync(root + '/assets/js/agent-workspace.js','utf8');
const dataCode = fs.readFileSync(root + '/assets/js/workspace-data.js','utf8');
['clientIntakeName','clientIntakePhone','clientIntakeEmail','clientIntakeProperty','clientIntakeReason','clientIntakeSource'].forEach(id=>assert(html.includes(`id="${id}"`), id));
assert(app.includes('renderClientIntake(snapshot)'));
assert(app.includes('408FARMERS handoff'));
const report = {assessment:'home',createdAt:'2026-07-27T00:00:00Z',score:80,consumer:{firstName:'Dylan',lastName:'Haysbert',name:'Dylan Haysbert',email:'d@example.com',phone:'4083276377',propertyAddress:'123 Main St, Fremont, CA',reviewContext:'Current policy renewal'},integration:{source:'408farmers',campaign:'door_hanger',entry:'home_lander_form',sessionId:'secret-session',prefilled:true},recommendations:[],strengths:[]};
const store = {getItem(k){return k==='coveragefit_home_report'?JSON.stringify(report):null;}};
const context={globalThis:{localStorage:store,dispatchEvent(){},CustomEvent:function(){},addEventListener(){},removeEventListener(){}},module:{exports:{}},console};
context.window=context.globalThis;
vm.runInNewContext(dataCode,context);
const snap=context.module.exports.getSnapshot({storage:store,propertyProfile:null});
assert.equal(snap.customer.propertyAddress,'123 Main St, Fremont, CA');
assert.equal(snap.customer.reviewContext,'Current policy renewal');
assert.equal(snap.integration.source,'408farmers');
assert.equal(snap.integration.sessionId,'secret-session');
assert.equal(snap.integration.prefilled,true);
console.log('CF-INT-1G QA: 13/13 passed');
