import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {authorizeIdentityReconciliation} from './server/pvx-web-reconciliation-core.mjs';
import {customerDocumentLibrary} from './server/pvx-customer-document-library-core.mjs';
import {projectCustomerProducerStatus} from './server/pvx-customer-producer-status-core.mjs';
import {pvxWebResumeCookie} from './server/pvx-web-journey-core.mjs';

if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.199');
const cookie=pvxWebResumeCookie(`pvxw_${'A'.repeat(43)}`);assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Lax/);
const contactOnly=authorizeIdentityReconciliation({phoneMatch:true,emailMatch:true});assert.equal(contactOnly.authorized,false);assert.equal(contactOnly.merge,false);assert.equal(contactOnly.contactMatchOnly,true);assert.equal(contactOnly.silentMerge,false);const linked=authorizeIdentityReconciliation({webJourneyId:'web',smsJourneyId:'sms',bootstrapLinkVerified:true});assert.equal(linked.authorized,true);assert.equal(linked.silentMerge,false);
const documents=customerDocumentLibrary({policyDocuments:[{documentId:'d1',originalName:'policy.pdf',mimeType:'application/pdf',size:100,createdAt:'2026-08-22T00:00:00Z',access:'private',customerAuthorized:true,status:'received',objectKey:'private/secret.pdf'},{documentId:'d2',access:'public',customerAuthorized:true,status:'received'},{documentId:'d3',access:'private',customerAuthorized:false,status:'received'}]});assert.equal(documents.length,1);assert.equal(documents[0].documentId,'d1');assert.ok(!('objectKey'in documents[0]));
const projection=projectCustomerProducerStatus({producerStatus:'spoke_with_customer',producerStatusHistory:[{createdAt:'2026-08-22T00:00:00Z'}],internalNotes:'private-note-value',suppressionState:'private-suppression-value'});assert.equal(projection.privacy.internalNotesExposed,false);assert.equal(projection.privacy.suppressionStateExposed,false);assert.doesNotMatch(JSON.stringify(projection),/private-note-value|private-suppression-value/);
const require=createRequire(import.meta.url),events=require('./assets/js/pvx-consumer-events.js'),values=new Map();globalThis.localStorage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)};const analytic=events.event('readiness_expressed',{stage:'snapshot',readinessState:'exploring',name:'Private Person',phone:'4085550100',email:'private@example.com',token:'secret'});assert.deepEqual(analytic.detail,{stage:'snapshot',readinessState:'exploring'});
const checkpoint=fs.readFileSync('server/pvx-checkpoint-core.mjs','utf8'),followup=fs.readFileSync('server/pvx-followup-preferences-core.mjs','utf8'),consent=fs.readFileSync('server/sms-consent-core.mjs','utf8'),owner=fs.readFileSync('server/pvx-producer-status-core.mjs','utf8'),webReturn=fs.readFileSync('assets/js/pvx-web-return.js','utf8'),bootstrap=fs.readFileSync('assets/js/pvx-web-bootstrap.js','utf8'),documentCore=fs.readFileSync('server/pvx-customer-document-library-core.mjs','utf8');assert.match(checkpoint,/reportSaved:false,contact:contactRequested/);assert.match(checkpoint,/sms:Boolean/);assert.match(checkpoint,/call:Boolean/);assert.match(checkpoint,/email:Boolean/);assert.match(followup,/global_suppression/);assert.match(followup,/action:'canceled'/);assert.match(consent,/provider suppression is authoritative/);assert.match(owner,/ownership_conflict/);assert.match(webReturn,/history\.replaceState/);assert.match(bootstrap,/history\.replaceState/);assert.match(documentCore,/Cache-Control':'private, no-store/);assert.ok(fs.existsSync('agent/workspace/index.html'));assert.ok(fs.existsSync('agent/sms-operations/index.html'));assert.ok(fs.existsSync('assessment/index.html'));assert.ok(fs.existsSync('home/report/index.html'));assert.ok(fs.existsSync('pvx/index.html'));
console.log(JSON.stringify({sprint:'CF-PVX-READY-3.2',pass:true,checks:39}));
