import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {SEMANTIC_BOUNDARIES,readinessState,normalizeActionReadiness,normalizeChangeScope} from './server/pvx-readiness-core.mjs';
import {buildProducerOpportunityProjection,validateProducerOpportunity} from './server/pvx-producer-opportunity-core.mjs';

if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.198');
for(const [key,value] of Object.entries(SEMANTIC_BOUNDARIES)){assert.equal(value,false,key);}
const empty=readinessState({});assert.equal(empty.currentActionReadiness,null);assert.equal(empty.currentChangeScope,null);assert.equal(empty.inferred,false);
assert.throws(()=>normalizeActionReadiness({state:'open_if_fit',sourceCheckpoint:'snapshot'}));assert.throws(()=>normalizeChangeScope({scope:'carrier',sourceCheckpoint:'snapshot'}));
const projection=buildProducerOpportunityProjection({checkpoint:{snapshot:{whatDylanWouldLookAtFirst:[{topicKey:'cost',label:'Cost-focused comparison'}]},consent:{contact:false}}});assert.equal(validateProducerOpportunity(projection),true);assert.equal(projection.currentActionReadiness,'unknown');assert.equal(projection.currentChangeScope,'unknown');assert.equal(projection.numericScore,null);assert.equal(projection.buyingPrediction,null);assert.equal(projection.eligibilityConclusion,null);assert.equal(projection.inferred,false);
const require=createRequire(import.meta.url),paths=require('./assets/js/pvx-respectful-pathways.js'),topics=require('./assets/js/pvx-review-topic-engine.js'),buyIn=require('./assets/js/pvx-recommendation-buy-in.js');const price=paths.derive({discovery:{answers:{improvementPriorities:['price_only']}},readiness:{state:'price_dependent'}});assert.equal(price.kind,'cost_focused');assert.equal(price.createsTopic,false);assert.equal(price.createsRecommendation,false);assert.equal(price.affectsProtectionScore,false);const exploring=paths.derive({readiness:{state:'exploring'}});assert.equal(exploring.negativeLabel,false);assert.match(exploring.customerNarrative,/own pace/);
const derived=topics.derive({answers:{improvementPriorities:['price_only']}});assert.equal(derived.length,1);assert.equal(derived[0].status,'worth_reviewing');assert.equal(derived[0].policyFinding,false);assert.equal(derived[0].recommendation,false);assert.equal(derived[0].recommendedLimit,null);assert.equal(topics.validateTopic(derived[0]),true);assert.equal(buyIn.eligible(derived[0]),false);assert.throws(()=>buyIn.capture(derived[0],'accepted_logic'));
const actual={status:'actual_recommendation',recommendation:true,evidenceRefs:[{source:'policy'}],authority:'existing_recommendation_engine',recommendationKey:'r1'},response=buyIn.capture(actual,'needs_explanation');assert.equal(response.bindAuthorization,false);assert.equal(response.topicResponse,false);
const sources=['pvx/snapshot/index.html','assets/js/pvx-respectful-pathways.js','assets/js/pvx-trigger-narrative.js','server/pvx-producer-opportunity-core.mjs'].map(file=>fs.readFileSync(file,'utf8')).join('\n');for(const prohibited of['hot lead','cold lead','unqualified','guaranteed savings','act now','last chance','your carrier failed'])assert.ok(!sources.toLowerCase().includes(prohibited));assert.match(sources,/not a review of your current policy/);assert.match(sources,/preserve what is working/);
console.log(JSON.stringify({sprint:'CF-PVX-READY-3.1',pass:true,checks:40}));
