import assert from 'node:assert/strict';
import fs from 'node:fs';
import {hashToken,campaignDispositionFor} from './server/pvx-checkpoint-core.mjs';
import {reminderDecision,handlePVXFollowUpPreferences} from './server/pvx-followup-preferences-core.mjs';

if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.190');
assert.equal(campaignDispositionFor({desiredNextActions:[{action:'continue_later'}]}),'continue_later');assert.equal(campaignDispositionFor({actionReadinessExpressions:[{state:'exploring'}]}),'exploring');assert.equal(campaignDispositionFor({}),'active');
const active={createdAt:'2026-08-22T00:00:00Z',contactRequestedAt:'2026-08-22T00:00:00Z',consent:{contact:true,sms:true,call:false,email:false},followUpReminders:[]};assert.equal(reminderDecision(active,'sms',new Date('2026-08-23T00:01:00Z')).allowed,true);assert.equal(reminderDecision({...active,globalDnc:true},'sms',new Date('2026-08-23T00:01:00Z')).reason,'global_suppression');assert.equal(reminderDecision({...active,smsSuppression:{status:'opted_out'}},'sms',new Date('2026-08-23T00:01:00Z')).allowed,false);assert.equal(reminderDecision({...active,followUpReminders:[{channel:'sms',sentAt:'2026-08-22T01:00:00Z'},{channel:'sms',sentAt:'2026-08-23T01:00:00Z'}]},'sms',new Date('2026-08-24T02:00:00Z')).reason,'bounded_limit_reached');

const token=`pvx_${'b'.repeat(43)}`,key=`pvx/checkpoint/${await hashToken(token)}`,records=new Map();records.set(key,{createdAt:'2026-08-22T00:00:00Z',expiresAt:'2027-08-22T00:00:00Z',snapshot:{title:'Your CoverageFit'},contact:{mobile:'4085550100',email:'customer@example.com',preferredMethod:'call'},consent:{reportSaved:true,contact:true,call:true,email:false,sms:false},producerNotification:{status:'pending'},leadCheckpoints:[{checkpointType:'snapshot_saved'}]});const store={get:async id=>structuredClone(records.get(id)),setJSON:async(id,value)=>records.set(id,structuredClone(value))};
const call=(action,extra={})=>handlePVXFollowUpPreferences(new Request('https://coveragefit.example/api/pvx/follow-up',{method:'POST',headers:{Origin:'https://coveragefit.example','Content-Type':'application/json'},body:JSON.stringify({token,action,...extra})}),{store,now:new Date('2026-08-22T02:00:00Z')});
let response=await call('decline_session',{sessionId:'session_12345678'}),body=await response.json();assert.equal(response.status,200);assert.equal(body.preferences.campaignDisposition,'contact_declined');assert.equal(body.preferences.contactRequested,true);assert.equal(body.preferences.globalDncChanged,false);assert.equal(body.preferences.globalSmsConsentChanged,false);assert.equal(records.get(key).leadCheckpoints.length,1);
response=await call('update_channel',{preferredMethod:'email'});body=await response.json();assert.equal(response.status,200);assert.equal(body.preferences.preferredMethod,'email');assert.equal(records.get(key).consent.email,true);assert.equal(records.get(key).consent.call,false);
response=await call('cancel_contact');body=await response.json();assert.equal(response.status,200);assert.equal(body.preferences.contactRequested,false);assert.equal(body.preferences.reportAvailable,true);assert.equal(body.preferences.selfServiceAvailable,true);assert.equal(records.get(key).producerNotification.status,'canceled');assert.equal(records.get(key).snapshot.title,'Your CoverageFit');
const client=fs.readFileSync('assets/js/pvx-followup-preferences.js','utf8'),snapshot=fs.readFileSync('pvx/snapshot/index.html','utf8'),progress=fs.readFileSync('pvx/progress/index.html','utf8');assert.ok(client.includes('No contact requested. Your Snapshot and self-service options remain available.'));assert.ok(snapshot.includes('pvx-followup-preferences.js'));assert.ok(progress.includes('Cancel my contact request'));for(const prohibited of['countdown','finish your application','act now','last chance'])assert.ok(!`${client}${snapshot}${progress}`.toLowerCase().includes(prohibited));
console.log(JSON.stringify({sprint:'CF-PVX-READY-LIVE-2.2',pass:true,checks:25}));
