import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import { evidenceThread, producerEvidenceProjection } from './server/pvx-evidence-thread-core.mjs';
const require=createRequire(import.meta.url),cards=require('./assets/js/pvx-review-topic-cards.js');
assert.ok(Number(fs.readFileSync('VERSION','utf8').trim().split('.')[2])>=154);
const topic={topicKey:'rebuild',label:'Rebuilding assumptions',status:'worth_reviewing',recommendation:false,evidenceRefs:['upgradeSummary'],becauseYouToldUs:'You updated the home.',whyWorthReviewing:'The home changed.',whatDylanWouldWantToUnderstand:'What changed?'};
const thread=evidenceThread(topic,2);
assert.equal(thread.scanLabel,'02');
assert.equal(thread.recommendation,false);
assert.equal(thread.severity,null);
const html=cards.renderCardHtml({...topic,scanOrder:2});
assert.match(html,/data-scan-order="02"/);
assert.match(html,/<details/);
assert.match(html,/Because you told us/);
const projection=producerEvidenceProjection([topic],[{topicKey:'rebuild',state:'relevant'}]);
assert.equal(projection[0].response.recordType,'topicResponse');
assert.equal(projection[0].response.recommendationResponse,false);
console.log(JSON.stringify({sprint:'CF-PVX-INSIGHT-1.2',pass:true,checks:9}));
