import assert from 'node:assert/strict';
import fs from 'node:fs';
import readiness from './assets/js/pvx-readiness-moment.js';
if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.178');
const values=new Map();const storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)};
const expression=readiness.express('exploring',{storage,now:new Date('2026-08-22T00:00:00Z'),expressionId:'pvr_test12345'});
assert.equal(expression.state,'exploring');
assert.equal(expression.sourceCheckpoint,'snapshot');
assert.equal(expression.source,'customer_entered');
assert.equal(readiness.read(storage).actionReadinessExpressions.length,1);
assert.equal(Object.keys(readiness.STATES).length,5);
assert.throws(()=>readiness.express('qualified',{storage}),/Unsupported/);
const html=fs.readFileSync('pvx/snapshot/index.html','utf8');
assert.ok(html.indexOf('id="pvxSnapshotContent"')<html.indexOf('id="pvxReadinessMoment"'));
assert.ok(html.indexOf('id="pvxReadinessMoment"')<html.indexOf('id="pvxNextValueTitle"'));
assert.ok(html.includes('Skip this'));
assert.ok(html.includes('It does not change your Snapshot or limit what you can do next.'));
assert.ok(!/qualified|hot lead|low intent|unlikely to buy/i.test(html));
const css=fs.readFileSync('assets/css/pvx-readiness-moment.css','utf8');
assert.ok(/min-height:48px/.test(css)&&/prefers-reduced-motion/.test(css));
console.log(JSON.stringify({sprint:'CF-PVX-READY-1.2',pass:true,checks:13}));
