import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const read = file => fs.readFileSync(file, 'utf8');
const discovery = require('./assets/js/pvx-discovery.js');
const css = read('assets/css/pvx-experience-foundation.css');
const hostCss = read('assets/css/pvx-host-aware.css');
const discoveryHtml = read('pvx/discovery/index.html');
const startHtml = read('pvx/start/index.html');
const snapshotHtml = read('pvx/snapshot/index.html');
const snapshotModel = read('assets/js/pvx-snapshot-model.js');
const resume = read('server/pvx-web-journey-core.mjs');
const pvxHtml = fs.readdirSync('pvx', { withFileTypes: true }).filter(item => item.isDirectory() && fs.existsSync(`pvx/${item.name}/index.html`)).map(item => read(`pvx/${item.name}/index.html`)).join('\n');

const version = read('VERSION').trim();
assert.match(version, /^3\.20\.\d+$/);
assert.ok(Number(version.split('.')[2]) >= 149);
assert.equal(JSON.parse(read('package.json')).version, version);
assert.equal(discovery.QUESTIONS.length, 8);
assert.equal(discovery.validateCatalog().valid, true);
assert.equal(discovery.validateCatalog().technicalTermsFound.length, 0);
assert.ok(discovery.QUESTIONS.filter(question => question.type === 'single').every(question => question.autoAdvance));
assert.ok(discovery.QUESTIONS.every(question => question.options.some(option => /not sure/i.test(option.label)) || ['shoppingReason','improvementPriorities'].includes(question.id)));
assert.match(discoveryHtml, /id="pvxDiscoveryBack"/);
assert.match(discoveryHtml, /aria-live="polite"/);
assert.ok(['Your goals','Your home','Your Snapshot'].every(stage => discovery.QUESTIONS.some(question => question.stage === stage)));
assert.doesNotMatch(discoveryHtml, /Question \d+ of \d+/);
assert.match(startHtml, /No account required/);
assert.doesNotMatch(startHtml, /name="(?:name|email|phone|mobile)"[^>]*required/);
assert.ok(snapshotHtml.indexOf('pvxSnapshotContent') < snapshotHtml.indexOf('id="pvxCheckpoint"'));
assert.match(snapshotModel, /contactRequiredToView:false/);
assert.match(css, /min-height:\s*44px/);
assert.match(css, /font-size:\s*16px/);
assert.match(css, /focus-visible/);
assert.match(css, /safe-area-inset-bottom/);
assert.match(`${css}\n${hostCss}`, /prefers-reduced-motion:\s*reduce/);
assert.doesNotMatch(pvxHtml, /<iframe\b/i);
assert.match(resume, /resolvePvxWebDestination/);
assert.match(resume, /currentStage/);
assert.match(resume, /HttpOnly/);
const essentialBytes = ['pvx/start/index.html','pvx/discovery/index.html','pvx/snapshot/index.html','assets/css/pvx-experience-foundation.css','assets/js/pvx-discovery.js','assets/js/pvx-snapshot-view.js'].reduce((sum, file) => sum + fs.statSync(file).size, 0);
assert.ok(essentialBytes < 100000, `essential PVX source budget exceeded: ${essentialBytes}`);
console.log(JSON.stringify({ sprint: '408-CF-PVX-WEB-2.3', pass: true, checks: 23, essentialBytes, browserRuntime: 'static-and-model-certified; installed browser binary unavailable' }));
