import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';

if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.196');
const require=createRequire(import.meta.url),governance=require('./assets/js/pvx-experiment-governance.js'),dashboard=require('./assets/js/pvx-readiness-pilot-dashboard.js'),registry=JSON.parse(fs.readFileSync('CF_PVX_EXPERIMENT_REGISTRY.json','utf8')),draft=registry.experiments[0];
assert.equal(registry.build,'CF-PVX-READY-LEARN-2.2');assert.equal(governance.validateExperiment(draft).valid,true);assert.equal(governance.canActivate(draft),false);
const active={...draft,status:'active',reviews:{semantic:'approved',accessibility:'approved',privacy:'approved'}};assert.equal(governance.canActivate(active),true);const paused=governance.pauseExperiment(active,'owner_guardrail');assert.equal(paused.status,'paused');assert.equal(paused.activeTrafficPercent,0);assert.equal(paused.pause.immediate,true);
for(const area of['question_placement','explanation_copy','action_labels','route_hooks'])assert.ok(governance.AREAS.includes(area));for(const choice of['exploring','not_sure','continue_later'])assert.ok(governance.REQUIRED_CHOICES.includes(choice));
for(const bad of[{...active,primaryMetric:'snapshot_saved'},{...active,guardrails:['conversion']},{...active,samplePlan:{...active.samplePlan,minimumReportableCohort:1}},{...active,stoppingRule:{...active.stoppingRule,completeObservationWindow:false}},{...active,choiceProtections:['continue_later']},{...active,hypothesis:'Use scarcity to increase contact'}])assert.equal(governance.validateExperiment(bad).valid,false);
const view=dashboard.model({journeys:20,readinessFunnel:[{key:'first_answer_to_snapshot',completed:15},{key:'snapshot_to_readiness',completed:9}],producerEconomics:{contactPlans:6,producerConnections:4,quotesStarted:3,quotesDelivered:2,outcomes:{bound:1}},continueLater:{returned:5},privacy:{minimumChangeScopeCohort:5},targetsEstablished:false});assert.deepEqual({journeys:view.journeys,snapshots:view.snapshots,readiness:view.readiness,contacts:view.contactPlans,connections:view.producerConnections,quotes:view.quotesStarted,bound:view.bound,returns:view.continueLaterReturns,target:view.targetsEstablished},{journeys:20,snapshots:15,readiness:9,contacts:6,connections:4,quotes:3,bound:1,returns:5,target:false});
const html=fs.readFileSync('agent/workspace/index.html','utf8'),templates=fs.readFileSync('CF_PVX_READY_PILOT_REVIEW_TEMPLATES.md','utf8');assert.ok(html.includes('Meaningful progress, not raw conversion'));assert.ok(html.includes('pvx-readiness-pilot-dashboard.js'));for(const phrase of['Dylan — weekly producer-quality review','Agency owner — experiment gate','Immediate pause tested','Conversion alone cannot override'])assert.ok(templates.includes(phrase));assert.doesNotMatch(JSON.stringify(registry),/"status": "active"|fake activity|countdown|default consent/i);
console.log(JSON.stringify({sprint:'CF-PVX-READY-LEARN-2.2',pass:true,checks:31}));
