import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
assert.ok(Number(fs.readFileSync('VERSION','utf8').trim().split('.')[2]) >= 153);
const html=fs.readFileSync('pvx/snapshot/index.html','utf8');
const css=fs.readFileSync('assets/css/pvx-insight-snapshot.css','utf8');
const model=require('./assets/js/pvx-snapshot-model.js');
assert.match(html,/Your CoverageFit<\/h1>/);
assert.match(html,/pvxSnapshotCount/);
assert.match(html,/pvxSnapshotPrimaryBecause/);
assert.match(html,/See why this appeared/);
assert.match(css,/\.pvx-snapshot-payoff/);
const empty=model.derive({answers:{}},[]);
assert.equal(empty.signalSurface.topicCount,0);
assert.equal(empty.signalSurface.countLabel,'No forced areas to review');
assert.equal(empty.contactRequiredToView,false);
assert.equal(empty.guardrails.protectionScoreCreated,false);
console.log(JSON.stringify({sprint:'CF-PVX-INSIGHT-1.1',pass:true,checks:10}));
