import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';

assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.200');
const required=['pvx/start/index.html','pvx/discovery/index.html','pvx/snapshot/index.html','pvx/continue/index.html','pvx/home-profile/index.html','pvx/policy/index.html','pvx/progress/index.html','agent/workspace/index.html','agent/sms-operations/index.html','functions/api/pvx/web-bootstrap.js','functions/api/pvx/readiness.js','functions/api/pvx/checkpoint.js','functions/api/pvx/progress.js','functions/api/pvx/producer-records.js','functions/api/pvx/insight-metrics.js'];for(const file of required)assert.ok(fs.existsSync(file),file);
const html=fs.readFileSync('pvx/snapshot/index.html','utf8');assert.ok(html.indexOf('pvxSnapshotContent')<html.indexOf('pvxReadinessMoment'));assert.ok(html.indexOf('pvxReadinessMoment')<html.indexOf('pvxContactRequest'));assert.match(html,/id="pvxReadinessSkip"/);assert.match(html,/id="pvxChangeScope"[^>]*hidden/);assert.match(html,/id="pvxContinueWithoutSave"/);assert.match(html,/Save my Snapshot/);assert.match(html,/This Snapshot reflects only what you told us/);
const require=createRequire(import.meta.url),topic=require('./assets/js/pvx-review-topic-engine.js'),buyIn=require('./assets/js/pvx-recommendation-buy-in.js');const review=topic.derive({answers:{improvementPriorities:['price_only']}})[0];assert.equal(review.recommendation,false);assert.equal(review.policyFinding,false);assert.equal(buyIn.eligible(review),false);
const ledger=fs.readFileSync('MASTER_PROGRESS_LEDGER.md','utf8');for(const sprint of['CF-PVX-READY-1.0','CF-PVX-READY-1.7','CF-PVX-OPP-2.3','CF-PVX-READY-LIVE-2.2','408-CF-PVX-RELEVANCE-1.2','CF-PVX-READY-LEARN-2.2','CF-PVX-READY-3.3'])assert.ok(ledger.includes(sprint),sprint);
const roadmap=fs.readFileSync('CF-PVX-READY-ROADMAP.md','utf8');for(const release of['19','20','21','22','23','24','25'])assert.match(roadmap,new RegExp(`\\| ${release} \\|.*\\| Complete \\|`));
const finalDocs=['FINAL_CROSS_REPOSITORY_E2E_CERTIFICATION_RELEASE_25.md','FINAL_CROSS_REPOSITORY_REGRESSION_COMPARISON_RELEASE_25.md','FINAL_PROTECTED_CORE_SMS_408_HASH_COMPARISON_RELEASE_25.md','FINAL_ACCESSIBILITY_PERFORMANCE_CERTIFICATION_RELEASE_25.md','FINAL_PRIVACY_SECURITY_CONSENT_IDENTITY_DOCUMENT_OWNERSHIP_CERTIFICATION.md','FINAL_WORKSPACE_OPERATIONS_PRODUCER_CONTEXT_CERTIFICATION.md','FINAL_LEGACY_COMPATIBILITY_ROLLBACK_CERTIFICATION_RELEASE_25.md','UPDATED_CUSTOM_DOMAIN_CLOUDFLARE_CUTOVER_RUNBOOK.md','READINESS_TO_OUTCOME_PILOT_MEASUREMENT_PLAN.md','FINAL_IMPLEMENTATION_SUMMARY_RELEASE_25.md'];for(const file of finalDocs)assert.ok(fs.existsSync(file),file);
assert.match(fs.readFileSync('server/pvx-web-journey-core.mjs','utf8'),/HttpOnly; Secure; SameSite=Lax/);assert.match(fs.readFileSync('server/pvx-checkpoint-core.mjs','utf8'),/authorization: \{ bindAuthorized: false \}/);assert.match(fs.readFileSync('server/pvx-producer-opportunity-core.mjs','utf8'),/numericScore:null/);assert.match(fs.readFileSync('server/pvx-insight-attribution-core.mjs','utf8'),/minimumChangeScopeCohort/);
console.log(JSON.stringify({sprint:'CF-PVX-READY-3.3',version:'3.20.200',pass:true,checks:47}));
