import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildInsightAttribution,PVX_READY_ATTRIBUTION_BUILD,PRIVACY_THRESHOLD} from './server/pvx-insight-attribution-core.mjs';

if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.195');
const event=(journeyId,sequence,name,detail={},minute=sequence)=>({recordType:'pvx_meaningful_signal_event',journeyId,sequence,name,detail,occurredAt:`2026-08-22T00:${String(minute).padStart(2,'0')}:00Z`});
const records=[];
for(let index=1;index<=6;index+=1){const id=`journey_${index}`,scope=index===6?'coverage_structure':'carrier';records.push(event(id,1,'hook_viewed',{entryType:index===1?'home_auto':'home',cohort:'route',prefillCohort:index<=3?'partial':'none'},0),event(id,2,'first_answered',{},1),event(id,3,'discovery_answered',{questionPosition:1},2),event(id,4,'snapshot_viewed',{},3),event(id,5,'topic_responded',{topicResponse:'relevant'},4),event(id,6,'readiness_expressed',{readinessState:index===6?'price_dependent':'open_if_fit'},5),event(id,7,'desired_action_selected',{desiredAction:index===2?'continue_later':'see_if_comparison_is_worthwhile'},6),event(id,8,'change_scope_expressed',{changeScope:scope},7));if(index!==2)records.push(event(id,9,'contact_plan_confirmed',{contactScope:'comparison'},8));if(index===2)records.push(event(id,9,'report_returned',{},12));}
records.push({recordType:'pvx_checkpoint',checkpointId:'checkpoint_1',attribution:{webJourneyId:'journey_1'},createdAt:'2026-08-22T00:08:00Z',contactRequestedAt:'2026-08-22T00:08:00Z',consent:{contact:true},leadCheckpoints:[{checkpointType:'home_profile_ready',createdAt:'2026-08-22T00:09:00Z'},{checkpointType:'coverage_review_ready',createdAt:'2026-08-22T00:10:00Z'}],producerOutcomeHistory:[{status:'contact_attempted',createdAt:'2026-08-22T00:09:00Z'},{status:'spoke_with_customer',createdAt:'2026-08-22T00:10:00Z'},{status:'quote_started',createdAt:'2026-08-22T00:11:00Z'},{status:'quote_prepared',createdAt:'2026-08-22T00:12:00Z'},{status:'bound',createdAt:'2026-08-22T00:13:00Z'}]});
const report=buildInsightAttribution(records);
assert.equal(report.build,PVX_READY_ATTRIBUTION_BUILD);assert.equal(PRIVACY_THRESHOLD,5);assert.equal(report.readinessFunnel.find(item=>item.key==='snapshot_to_readiness').completed,6);assert.equal(report.readinessFunnel.find(item=>item.key==='desired_action_to_contact_plan').completed,5);assert.equal(report.readinessFunnel.find(item=>item.key==='contact_plan_to_producer_connection').completed,1);assert.equal(report.producerEconomics.contactPlans,5);assert.equal(report.producerEconomics.producerConnections,1);assert.equal(report.producerEconomics.quotesStarted,1);assert.equal(report.producerEconomics.quotesDelivered,1);assert.equal(report.producerEconomics.outcomes.bound,1);assert.equal(report.completion.homeProfile,1);assert.equal(report.completion.policyReview,1);assert.equal(report.readinessCohorts.prefill.partial.journeys,3);assert.equal(report.readinessOutcomes.open_if_fit.expressed,5);assert.equal(report.changeScopeOutcomes.carrier.suppressed,false);assert.equal(report.changeScopeOutcomes.carrier.expressed,5);assert.equal(report.changeScopeOutcomes.coverage_structure.suppressed,true);assert.equal(report.continueLater.selected,1);assert.equal(report.continueLater.returned,1);assert.equal(report.continueLater.treatedAsAbandonment,false);assert.equal(report.bundleContext.journeys,1);assert.equal(report.timing.timeToSnapshot.buckets['3_to_5m'],6);assert.equal(report.timing.contactToProducerResponse.buckets['1_to_3m'],1);assert.equal(report.targetsEstablished,false);assert.equal(report.producerEconomics.rawContactsAreSuccessTarget,false);assert.equal(report.semantics.readinessIsBuyingPrediction,false);assert.equal(report.semantics.scopeValuesRanked,false);assert.doesNotMatch(JSON.stringify(report),/journey_1|checkpoint_1|customer@example|exactCustomerWords|internalNotes/);
console.log(JSON.stringify({sprint:'CF-PVX-READY-LEARN-2.1',pass:true,checks:32}));
