import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';

if(process.env.COVERAGEFIT_REGRESSION!=='1')assert.equal(fs.readFileSync('VERSION','utf8').trim(),'3.20.197');
const require=createRequire(import.meta.url),moment=require('./assets/js/pvx-readiness-moment.js'),chooser=require('./assets/js/pvx-next-action-chooser.js');
const html=fs.readFileSync('pvx/snapshot/index.html','utf8'),readinessCss=fs.readFileSync('assets/css/pvx-readiness-moment.css','utf8'),foundation=fs.readFileSync('assets/css/pvx-experience-foundation.css','utf8'),journey=fs.readFileSync('assets/js/pvx-experience-foundation.js','utf8'),returnJs=fs.readFileSync('assets/js/pvx-web-return.js','utf8'),server=fs.readFileSync('server/pvx-web-journey-core.mjs','utf8'),events=fs.readFileSync('assets/js/pvx-readiness-moment.js','utf8');
assert.ok(html.indexOf('pvxSnapshotContent')<html.indexOf('pvxReadinessMoment'));assert.ok(html.indexOf('pvxReadinessMoment')<html.indexOf('pvxCheckpoint'));assert.match(html,/Optional — set the pace/);assert.match(html,/id="pvxReadinessSkip"/);assert.match(html,/data-change-scope="coverage_structure"/);assert.match(html,/data-change-scope="carrier"/);assert.match(html,/data-change-scope="either"/);assert.match(html,/data-change-scope="not_sure"/);assert.match(html,/id="pvxChangeScopeSkip"/);assert.match(html,/id="pvxChangeScope"[^>]*hidden/);assert.equal(Object.keys(moment.STATES).length,5);assert.ok(moment.STATES.exploring);assert.ok(moment.STATES.not_sure);assert.equal(chooser.relevant('understand_snapshot'),false);assert.equal(chooser.relevant('see_if_comparison_is_worthwhile'),true);assert.equal(chooser.relevant('become_quote_ready'),true);assert.match(readinessCss,/min-height:48px/);assert.match(readinessCss,/font-size:1rem/);assert.match(readinessCss,/max-width:680px/);assert.match(readinessCss,/prefers-reduced-motion:reduce/);assert.match(foundation,/min-height: 44px/);assert.match(foundation,/font-size: 16px/);assert.match(foundation,/safe-area-inset-bottom/);assert.match(foundation,/prefers-reduced-motion: reduce/);assert.match(journey,/pvxBack/);assert.match(returnJs,/history\.replaceState/);assert.match(server,/HttpOnly; Secure; SameSite=Lax/);assert.match(server,/currentStage/);assert.match(server,/currentStep/);assert.match(fs.readFileSync('server/pvx-checkpoint-core.mjs','utf8'),/exactStage/);assert.match(events,/readiness_prompt_viewed/);assert.doesNotMatch(fs.readFileSync('assets/js/pvx-snapshot-view.js','utf8'),/setTimeout|fake analysis|artificial delay/i);assert.match(html,/This Snapshot reflects only what you told us/);
console.log(JSON.stringify({sprint:'CF-PVX-READY-3.0',pass:true,checks:32}));
