import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {mapWebToPvx,validateWebPvxMapping} from './server/web-pvx-mapping-core.mjs';
import {mapSmsToPvx,validateSmsPvxMapping} from './server/sms-pvx-mapping-core.mjs';
import {buildCombinedReview,revisionStory} from './server/pvx-revision-story-core.mjs';
import {lifeEventPlan,applyProposedFacts} from './server/pvx-life-event-core.mjs';
import {nextUsefulUnlock} from './server/pvx-next-unlock-core.mjs';
const require=createRequire(import.meta.url),topicEngine=require('./assets/js/pvx-review-topic-engine.js'),snapshotModel=require('./assets/js/pvx-snapshot-model.js'),orchestrator=require('./assets/js/pvx-multipath-orchestrator.js'),continuation=require('./assets/js/pvx-continuation.js');
const farmers=path.resolve(process.env.FARMERS408_ROOT||'../408farmers');
const entries=[
  ['homepage','start_snapshot'],['home','review_owned_home'],['buyer','buying_home'],['home_auto','review_home_auto'],['professional','review_professional_home'],['flyer','start_snapshot'],['qr','start_snapshot'],['neighbor','start_snapshot'],['direct','start_snapshot']
];
for(const[entry_type,customer_selection]of entries){const mapping=mapWebToPvx({entry_type,customer_selection,bootstrap_id:'pvxb_abcdefghijklmnop',customer_words:`Selected ${customer_selection}`});assert.equal(validateWebPvxMapping(mapping).valid,true,entry_type);assert.equal(mapping.canEnterPvx,true,entry_type);assert.equal(mapping.consent.contact,false);assert.equal(mapping.semantics.discoveryAffectsProtectionScore,false);}
const buyer=mapWebToPvx({entry_type:'buyer',customer_selection:'buying_home'});assert.equal(buyer.discovery.answers.shoppingReason,'buying_home');assert.equal(buyer.discovery.answers.ownershipDuration,'buying_now');
const bundle=mapWebToPvx({entry_type:'home_auto',customer_selection:'review_home_auto'});assert.equal(bundle.context.bundle.active,true);
const professional=mapWebToPvx({entry_type:'professional',customer_selection:'review_professional_home',professional_program:'teachers'});assert.equal(professional.context.professional.eligibilityDetermined,false);assert.equal(professional.context.professional.discountDetermined,false);
for(const intent of['buyer','home_review','bundle']){const sms=mapSmsToPvx({intent,conversationId:`sms_${intent}`,answers:{reviewReason:'price'},customerWords:[{direction:'inbound',body:'My own words'}]});assert.equal(validateSmsPvxMapping(sms).valid,true);assert.equal(sms.canEnterPvx,true);assert.equal(sms.contact.callConsent,false);assert.equal(sms.contact.emailConsent,false);}
const ambiguous=mapSmsToPvx({intent:'',conversationId:'sms_ambiguous'});assert.equal(ambiguous.producerSafeFallback,true);
const ai=mapWebToPvx({entry_type:'ai_caller',customer_selection:'secure_continue',conversation_intent:'buyer',conversation_id:'ai_1',conversation_answers:{stayIntent:'long_term'},customer_words:'We are buying and plan to stay.'});assert.equal(validateWebPvxMapping(ai).valid,true);assert.equal(ai.discovery.currentQuestionId,'improvementPriorities');
const topicCases=[{answers:{}},{answers:{stayIntent:'long_term'}},{answers:{stayIntent:'long_term',improvementPriorities:['agent_access']}},{answers:{stayIntent:'long_term',improvementPriorities:['agent_access'],otherProperties:'rental',ownershipDuration:'10_plus',upgradeSummary:'yes_major'}}];topicCases.forEach((discovery,count)=>{const model=snapshotModel.derive(discovery,topicEngine.derive(discovery,{}));assert.equal(model.signalSurface.topicCount,count);assert.equal(model.guardrails.policyDeficiencyFound,false);});
let state=orchestrator.create();assert.equal(orchestrator.nextAction(state).action,'choose_optional_path');state=orchestrator.complete(orchestrator.start(state,'home_profile'),'home_profile');assert.equal(nextUsefulUnlock({homeProfilePath:{status:'complete'}}).primary.path,'current_policy');let policyFirst=orchestrator.complete(orchestrator.start(orchestrator.create(),'current_policy'),'current_policy');assert.equal(nextUsefulUnlock({currentPolicyPath:{status:'complete'}}).primary.path,'home_profile');state=orchestrator.complete(orchestrator.start(state,'current_policy'),'current_policy');assert.equal(state.combinedReview,'ready');policyFirst=orchestrator.complete(orchestrator.start(policyFirst,'home_profile'),'home_profile');assert.equal(policyFirst.combinedReview,'ready');assert.equal(orchestrator.nextAction(state).path,'combined');assert.equal(orchestrator.assist(orchestrator.create()).mode,'producer_assisted');assert.equal(orchestrator.nextAction(orchestrator.pause(orchestrator.create())).action,'secure_return');
for(const choice of continuation.CHOICES)assert.equal(continuation.validate(continuation.payload(`pvx_${'A'.repeat(43)}`,choice)).valid,true);assert.equal(nextUsefulUnlock({resumeState:{status:'paused'},explicitContinuationChoice:'continue_later'}).primary.action,'continue_later');assert.equal(nextUsefulUnlock({explicitContinuationChoice:'producer_assisted'}).primary.action,'producer_assisted');
const homeRevision={revisionId:'2H_a',revision:'2H',contents:{propertyFacts:{}}},policyRevision={revisionId:'2P_b',revision:'2P',contents:{coverageInformationReceived:{}}},record={snapshot:snapshotModel.derive({},[]),reportRevisions:[homeRevision,policyRevision],homeProfile:{},currentPolicyProfile:{},coverageReview:{findings:[]},recommendations:[]};const combined=buildCombinedReview(record,'2026-08-22T00:00:00Z');assert.equal(combined.revision,'3');assert.deepEqual(combined.contents.revisionStory.from,['2H_a','2P_b']);assert.deepEqual(revisionStory({...record,reportRevisions:[policyRevision,homeRevision,combined]}).map(item=>item.revision),['1','2P','2H','3']);
assert.equal(lifeEventPlan('renovated').path,'home_profile');assert.equal(lifeEventPlan('insurance_changed').path,'current_policy');assert.equal(lifeEventPlan('vehicle').producerSafe,true);const conflicts=applyProposedFacts({yearBuilt:{value:1988,source:'customer_confirmed'}},{yearBuilt:{value:1990}});assert.equal(conflicts.conflicts.length,1);assert.equal(conflicts.facts.yearBuilt.value,1988);
for(const file of['home/assessment-config.js','assets/js/protection-score.js','assets/js/workspace-data.js','server/sms-operations-core.mjs','server/ringcentral-sms-connection-core.mjs','server/prospect-report-core.mjs'])assert(fs.existsSync(file));for(const file of['index.html','home/index.html','buyer/index.html','auto-bundle/index.html','healthcare/index.html','teachers/index.html','tech/index.html','engineers/index.html','neighbor/index.html'])assert(fs.existsSync(path.join(farmers,file)));for(const file of['life/index.html','local/index.html'])assert.doesNotMatch(fs.readFileSync(path.join(farmers,file),'utf8'),/data-pvx-native-mount/);const manifest=JSON.parse(fs.readFileSync(path.join(farmers,'handoff-manifest.json'),'utf8'));assert.equal(manifest.nativeWebConvergence.integrationRelease,'408-CF-PVX-HOOK-1.3');assert.equal(manifest.nativeWebConvergence.receiver,'CoverageFit v3.20.168');
console.log('CF-PVX-INSIGHT-3.3 QA: PASS');
