import assert from 'node:assert/strict';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { referralKey } from './server/referral-link-core.mjs';
import { resolvePvxWebReferralContext } from './server/pvx-web-journey-core.mjs';

const now = new Date('2026-08-21T12:00:00.000Z');
const token = 'ref_abcdefghijklmnop';
const record = { schemaVersion:'1.0', referralType:'neighbor', createdAt:'2026-08-01T00:00:00.000Z', expiresAt:'2026-09-01T00:00:00.000Z', origin:{ campaignId:'neighbor_origin', campaignVariant:'fit', campaignZip:'94539' } };
const store = { async get(key) { return key === await referralKey(token) ? record : null; } };
const verified = await resolvePvxWebReferralContext({ entry_type:'neighbor', referral_token:token }, { referralStore:store, now });
assert.equal(verified.status, 'verified');
assert.match(verified.source.referral_id, /^nref_/);
assert.equal(verified.source.referral_token, undefined);
assert.equal(verified.source.campaign_id, 'neighbor_origin');
const invalid = await resolvePvxWebReferralContext({ entry_type:'neighbor', referral_token:'bad-token' }, { referralStore:store, now });
assert.equal(invalid.status, 'generic_fallback');
assert.equal(invalid.source.referral_token, undefined);
const expired = await resolvePvxWebReferralContext({ entry_type:'neighbor', referral_token:token }, { referralStore:{ async get(){ return {...record, expiresAt:'2026-08-20T00:00:00.000Z'}; } }, now });
assert.equal(expired.status, 'generic_fallback');
const root = path.dirname(fileURLToPath(import.meta.url));
const farmersRoot = process.env.FARMERS408_ROOT || path.resolve(root, '../408farmers');
const mod = await import(pathToFileURL(path.join(farmersRoot, 'shared/referral-bridge.js')));
const api = mod.default || globalThis.Farmers408ReferralBridge;
const route = api.readRoute({ pathname:`/neighbor/r/${token}`, search:'?share=sms' });
const payload = api.buildPayload(route, { storage:{ getItem(){return 'pvxb_1234567890abcdef';},setItem(){} } });
assert.equal(payload.referral_token, token);
assert.equal(payload.entry_type, 'neighbor');
assert.equal(api.buildDestination(route), 'https://review.408farmers.com/api/pvx/web-bootstrap');
assert.ok(!api.buildDestination(route).includes(token));
console.log(JSON.stringify({ sprint:'408-CF-PVX-WEB-1.8', pass:true, checks:13 }));
