#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RESEND_EMAIL_ENDPOINT, buildNewReviewEmail, notificationConfig, normalizeNotification, sendNewReviewNotification, shouldAttemptNewReviewNotification } from './server/producer-notification.mjs';
import { handleConsultationSubmission, normalizeStoredRecord, RECORD_VERSION } from './server/consultation-inbox-core.mjs';
const root = path.dirname(fileURLToPath(import.meta.url));
const checks=[]; const check=(n,v)=>{assert.ok(v,n);checks.push(n)}; const read=f=>fs.readFileSync(path.join(root,f),'utf8'); const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
check('release version',['3.20.7','3.20.8','3.20.10','3.20.11','3.20.12','3.20.13','3.20.14','3.20.15','3.20.17','3.20.18','3.20.19','3.20.20','3.20.21','3.20.22','3.20.23','3.20.24','3.20.25','3.20.26','3.20.27','3.20.28','3.20.29','3.20.30','3.20.31','3.20.32','3.20.33','3.20.34','3.20.35','3.20.36','3.20.37','3.20.38','3.20.39','3.20.40','3.20.41','3.20.42','3.20.43','3.20.44','3.20.45','3.20.46','3.20.47','3.20.48','3.20.49','3.20.50','3.20.51','3.20.52','3.20.53','3.20.54','3.20.55','3.20.56','3.20.57','3.20.58','3.20.59','3.20.60'].includes(read('VERSION').trim())&&['3.20.7','3.20.8','3.20.10','3.20.11','3.20.12','3.20.13','3.20.14','3.20.15','3.20.17','3.20.18','3.20.19','3.20.20','3.20.21','3.20.22','3.20.23','3.20.24','3.20.25','3.20.26','3.20.27','3.20.28','3.20.29','3.20.30','3.20.31','3.20.32','3.20.33','3.20.34','3.20.35','3.20.36','3.20.37','3.20.38','3.20.39','3.20.40','3.20.41','3.20.42','3.20.43','3.20.44','3.20.45','3.20.46','3.20.47','3.20.48','3.20.49','3.20.50','3.20.51','3.20.52','3.20.53','3.20.54','3.20.55','3.20.56','3.20.57','3.20.58','3.20.59','3.20.60'].includes(JSON.parse(read('package.json')).version));
check('release docs',read('CHANGELOG.md').includes('CONS-2.1 Privacy-Safe New Review Notification')&&read('ROADMAP.md').includes('CONS-2.1 Privacy-Safe New Review Notification — Complete (3.20.7)')&&read('README.md').includes('CONS-2.1'));
check('sprint files',fs.existsSync(path.join(root,'SPRINT-CONS-2.1.md'))&&fs.existsSync(path.join(root,'NEW-REVIEW-NOTIFICATION.md')));
check('setup variables',['RESEND_API_KEY','COVERAGEFIT_PRODUCER_NOTIFICATION_EMAIL','COVERAGEFIT_NOTIFICATION_FROM','COVERAGEFIT_NEW_REVIEW_NOTIFICATIONS_ENABLED'].every(x=>read('CLOUDFLARE-SETUP.md').includes(x)));
check('record version',['1.5.0','1.6.0','1.7.0','1.8.0'].includes(RECORD_VERSION));
check('workspace states',['Producer email alert sent','Producer email alert delivery failed','Producer email alert not configured','Producer email alert history is unavailable'].every(x=>read('assets/js/agent-workspace.js').includes(x)));
const requestUrl='https://preview.coveragefit.com/api/consultations/submit';
const env={RESEND_API_KEY:'re_test_abcdefghijklmnopqrstuvwxyz',COVERAGEFIT_PRODUCER_NOTIFICATION_EMAIL:'dylan@dylanhaysbert.com',COVERAGEFIT_NOTIFICATION_FROM:'CoverageFit <reviews@coveragefit.com>'};
const cfg=notificationConfig(env,requestUrl); const email=buildNewReviewEmail(cfg);
check('preview origin',cfg.configured&&cfg.workspaceUrl==='https://preview.coveragefit.com/agent/workspace/');
check('generic subject',email.subject==='New CoverageFit review ready');
const pii=['Alice Prospect','alice@example.com','123 Main Street','Protection Score 87','Water Backup'];
check('privacy-safe body',pii.every(x=>!`${email.subject}${email.text}${email.html}`.includes(x))&&email.text.includes('intentionally excludes'));
check('disabled skipped',(await sendNewReviewNotification({id:'consultation-disabled-123456'},{env:{...env,COVERAGEFIT_NEW_REVIEW_NOTIFICATIONS_ENABLED:'false'},requestUrl})).state==='skipped');
check('missing config skipped',(await sendNewReviewNotification({id:'consultation-missing-123456'},{env:{},requestUrl})).reason==='not_configured');
check('state rules',normalizeNotification(null).state==='legacy'&&!shouldAttemptNewReviewNotification({state:'sent'})&&shouldAttemptNewReviewNotification({state:'failed'})&&!shouldAttemptNewReviewNotification({state:'legacy'}));
let calls=[]; const fetchOk=async(url,init)=>{calls.push({url,init:{...init,signal:undefined}});return new Response(JSON.stringify({id:'email_123'}),{status:200,headers:{'Content-Type':'application/json'}})};
const sent=await sendNewReviewNotification({id:'consultation-alpha-123456'},{env,requestUrl,fetch:fetchOk});
check('send success',sent.state==='sent'&&sent.providerMessageId==='email_123'&&calls.length===1&&calls[0].url===RESEND_EMAIL_ENDPOINT);
check('auth and idempotency',calls[0].init.headers.Authorization===`Bearer ${env.RESEND_API_KEY}`&&calls[0].init.headers['Idempotency-Key']==='coveragefit-new-review-consultation-alpha-123456');
const payload=JSON.parse(calls[0].init.body); check('configured routing',payload.from===env.COVERAGEFIT_NOTIFICATION_FROM&&payload.to[0]===env.COVERAGEFIT_PRODUCER_NOTIFICATION_EMAIL); check('provider payload private',pii.every(x=>!JSON.stringify(payload).includes(x)));
let retry=0; const recovered=await sendNewReviewNotification({id:'consultation-retry-123456'},{env,requestUrl,fetch:async()=>{retry++;return retry===1?new Response('{}',{status:503}):new Response(JSON.stringify({id:'retry_ok'}),{status:200,headers:{'Content-Type':'application/json'}})}}); check('bounded retry',recovered.state==='sent'&&retry===2);
let rejected=0; const rejectedState=await sendNewReviewNotification({id:'consultation-rejected-123456'},{env,requestUrl,fetch:async()=>{rejected++;return new Response('{}',{status:400})}}); check('permanent rejection',rejectedState.state==='failed'&&rejectedState.reason==='provider_rejected'&&rejected===1);
function store(){const rows=new Map(),writes=[];return{rows,writes,async get(k){return clone(rows.get(k)||null)},async setJSON(k,v,o={}){rows.set(k,clone(v));writes.push({k,v:clone(v),metadata:clone(o.metadata)})},async list(){return{blobs:[...rows.keys()].map(key=>({key}))}}}}
function report(id='consultation-newreview-123456'){return{version:'3.20.7',assessment:'home',createdAt:'2026-08-03T06:20:00.000Z',score:87,status:'Strong Foundation',strongest:'Liability review history',topPriority:'Water Backup',consumer:{name:'Alice Prospect',firstName:'Alice',lastName:'Prospect',email:'alice@example.com',phone:'4085550101',propertyAddress:'123 Main Street',reviewContext:'Annual renewal'},consultationRecord:{id,createdAt:'2026-08-03T06:20:00.000Z'},recommendations:[{title:'Water Backup'}]}}
function req(body){return new Request(requestUrl,{method:'POST',headers:{Origin:'https://preview.coveragefit.com','Content-Type':'application/json'},body:JSON.stringify(body)})}
const s=store();let integration=0;const response=await handleConsultationSubmission(req({record:report()}),{store:s,env,fetch:async()=>{integration++;return new Response(JSON.stringify({id:'integration_123'}),{status:200,headers:{'Content-Type':'application/json'}})}});const body=await response.json();const stored=s.rows.get('records/consultation-newreview-123456');
check('submission success',response.status===201&&body.ok&&integration===1);
check('stored sent state',stored.notification.state==='sent'&&stored.notification.providerMessageId==='integration_123'&&!('to'in stored.notification)&&!('from'in stored.notification));
check('sent activity and metadata',stored.activity.some(e=>e.type==='producer_notified')&&s.writes.at(-1).metadata.notificationState==='sent');
await handleConsultationSubmission(req({record:report()}),{store:s,env,fetch:async()=>{integration++;return new Response('{}',{status:200})}}); check('duplicate suppressed',integration===1&&s.rows.get('records/consultation-newreview-123456').activity.filter(e=>e.type==='producer_notified').length===1);
const failStore=store();let failCalls=0;const failResponse=await handleConsultationSubmission(req({record:report('consultation-failure-123456')}),{store:failStore,env,fetch:async()=>{failCalls++;return new Response('{}',{status:503})}});check('failure nonblocking',failResponse.status===201&&failCalls===2&&failStore.rows.get('records/consultation-failure-123456').notification.state==='failed'&&!failStore.rows.get('records/consultation-failure-123456').activity.some(e=>e.type==='producer_notified'));
let recovery=0;await handleConsultationSubmission(req({record:report('consultation-failure-123456')}),{store:failStore,env,fetch:async()=>{recovery++;return new Response(JSON.stringify({id:'recovered'}),{status:200,headers:{'Content-Type':'application/json'}})}});check('failed retry recovers',recovery===1&&failStore.rows.get('records/consultation-failure-123456').notification.state==='sent');
const noCfg=store();const noCfgResponse=await handleConsultationSubmission(req({record:report('consultation-unconfigured-123456')}),{store:noCfg,env:{}});check('unconfigured nonblocking',noCfgResponse.status===201&&noCfg.rows.get('records/consultation-unconfigured-123456').notification.state==='skipped');
const bgStore=store();const backgroundTasks=[];let releaseProvider;const providerGate=new Promise(resolve=>{releaseProvider=resolve});const bgResponse=await handleConsultationSubmission(req({record:report('consultation-background-123456')}),{store:bgStore,env,waitUntil:promise=>backgroundTasks.push(promise),fetch:async()=>{await providerGate;return new Response(JSON.stringify({id:'background_sent'}),{status:200,headers:{'Content-Type':'application/json'}})}});check('Cloudflare response does not wait for provider',bgResponse.status===201&&backgroundTasks.length===1&&bgStore.rows.get('records/consultation-background-123456').notification.state==='pending');releaseProvider();await Promise.all(backgroundTasks);check('background delivery persists final state',bgStore.rows.get('records/consultation-background-123456').notification.state==='sent'&&bgStore.rows.get('records/consultation-background-123456').activity.some(e=>e.type==='producer_notified'));
const spam=store();let spamCalls=0;const spamResponse=await handleConsultationSubmission(req({website:'spam',record:report('consultation-spam-123456')}),{store:spam,env,fetch:async()=>{spamCalls++;return new Response('{}',{status:200})}});check('honeypot no alert',spamResponse.status===202&&spam.rows.size===0&&spamCalls===0);
const legacy=normalizeStoredRecord({id:'consultation-legacy-123456',product:'home',status:'new',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',customer:{name:'Legacy',email:'legacy@example.com'},assessment:{},integration:{},report:report('consultation-legacy-123456')});check('legacy compatibility',legacy.notification.state==='legacy'&&!legacy.activity.some(e=>e.type==='producer_notified'));
console.log(`CONS-2.1 QA: ${checks.length}/${checks.length} passed`);
