import fs from 'node:fs';
import { operationsStatus, redactLogText, handleSmsOperations, queueSmsRetry, updateWebhookHealth, SMS_OPERATIONS_BUILD } from './server/sms-operations-core.mjs';
import { SMS_ENGINE_BUILD, SMS_ENGINE_VERSION } from './server/sms-conversation-core.mjs';
import { SMS_HANDOFF_BUILD, createSmsHandoff, handleSmsHandoffRead } from './server/sms-handoff-core.mjs';
import { RC_SMS_CONNECTION_BUILD } from './server/ringcentral-sms-connection-core.mjs';
import { SMS_PRODUCER_HANDOFF_BUILD } from './server/sms-producer-handoff-core.mjs';
import { handleProspectReportCreate } from './server/prospect-report-core.mjs';
const checks=[];const check=(n,v)=>{if(!v)throw new Error(n);checks.push(n)};
class Store{constructor(){this.m=new Map()}async get(k){return this.m.get(String(k))||null}async setJSON(k,v,o={}){k=String(k);if(o.onlyIfNew&&this.m.has(k))throw new Error('UNIQUE');this.m.set(k,JSON.parse(JSON.stringify(v)))}async delete(k){this.m.delete(String(k))}async list({prefix='',limit=500}={}){return{blobs:[...this.m.keys()].filter(k=>k.startsWith(prefix)).slice(0,limit).map(key=>({key,uploadedAt:this.m.get(key)?.updatedAt||this.m.get(key)?.createdAt||''}))}}}
check('release',['3.20.27','3.20.28','3.20.29','3.20.30','3.20.31','3.20.32','3.20.33','3.20.34','3.20.35','3.20.36','3.20.37','3.20.38','3.20.39','3.20.40','3.20.41','3.20.42','3.20.43','3.20.44','3.20.45','3.20.46','3.20.47','3.20.48','3.20.49','3.20.50','3.20.51','3.20.52','3.20.53','3.20.54','3.20.55','3.20.56','3.20.57','3.20.58','3.20.59','3.20.60','3.20.67','3.20.68','3.20.69','3.20.70','3.20.71','3.20.72','3.20.73','3.20.74','3.20.75','3.20.76','3.20.77','3.20.78','3.20.79','3.20.80','3.20.81','3.20.82','3.20.83'].includes(fs.readFileSync('VERSION','utf8').trim())&&['3.20.27','3.20.28','3.20.29','3.20.30','3.20.31','3.20.32','3.20.33','3.20.34','3.20.35','3.20.36','3.20.37','3.20.38','3.20.39','3.20.40','3.20.41','3.20.42','3.20.43','3.20.44','3.20.45','3.20.46','3.20.47','3.20.48','3.20.49','3.20.50','3.20.51','3.20.52','3.20.53','3.20.54','3.20.55','3.20.56','3.20.57','3.20.58','3.20.59','3.20.60','3.20.67','3.20.68','3.20.69','3.20.70','3.20.71','3.20.72','3.20.73','3.20.74','3.20.75','3.20.76','3.20.77','3.20.78','3.20.79','3.20.80','3.20.81','3.20.82','3.20.83'].includes(JSON.parse(fs.readFileSync('package.json','utf8')).version));
check('build sync',['1.7.0','1.7.1','1.7.2'].includes(SMS_ENGINE_VERSION)&&[SMS_ENGINE_BUILD,SMS_HANDOFF_BUILD,RC_SMS_CONNECTION_BUILD,SMS_PRODUCER_HANDOFF_BUILD,SMS_OPERATIONS_BUILD].every(x=>['RC-SMS-1.9','RC-SMS-1.9.1','RC-SMS-1.9.2','RC-SMS-1.9.3','RC-SMS-1.9.4','RC-SMS-1.9.5','RC-SMS-1.9.6'].includes(x)));
check('dashboard files',fs.existsSync('agent/sms-operations/index.html')&&fs.existsSync('assets/js/sms-operations.js')&&fs.existsSync('functions/api/sms/operations/index.js'));
const now=new Date('2026-08-06T20:30:00Z');
check('status new',operationsStatus({state:'new',updatedAt:now.toISOString()},now)==='new');
check('status active',operationsStatus({state:'buyer_address_requested',updatedAt:now.toISOString()},now)==='active');
check('status link',operationsStatus({state:'awaiting_producer',handoff:{url:'https://coveragefit.com/x'},updatedAt:now.toISOString()},now)==='link_delivered');
check('status started',operationsStatus({state:'awaiting_producer',coverageFitStartedAt:now.toISOString(),updatedAt:now.toISOString()},now)==='coveragefit_started');
check('status complete',operationsStatus({state:'awaiting_producer',coverageFitCompletedAt:now.toISOString(),updatedAt:now.toISOString()},now)==='coveragefit_completed');
check('status failed',operationsStatus({state:'active',deliveryFailure:{code:'x'},updatedAt:now.toISOString()},now)==='failed');
check('status stale',operationsStatus({state:'buyer_address_requested',updatedAt:'2026-08-04T00:00:00Z'},now,24)==='stale');
check('redaction',redactLogText('Call +1 408-555-1212 at 123 Main Street').includes('[phone]')&&redactLogText('Call +1 408-555-1212 at 123 Main Street').includes('[address]'));
const store=new Store();
const cid='sms-live-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
await store.setJSON(`sms-live-conversations/${cid}`,{id:cid,state:'awaiting_producer',intent:'buyer',contactPhone:'+14085551212',answers:{priority:'rush'},attribution:{partnerId:'jm',partnerName:'Jessica'},handoff:{url:'https://coveragefit.com/sms/continue/?token=opaque'},createdAt:'2026-08-06T20:00:00Z',updatedAt:'2026-08-06T20:10:00Z'});
await updateWebhookHealth(store,{success:true},{now});
await queueSmsRetry(store,{conversationId:cid,to:'+14085551212',body:'test message',error:'send failed'},{now});
const env={COVERAGEFIT_PRODUCER_ACCESS_TOKEN:'producer-access-token-1234567890'};
const req=new Request('https://coveragefit.com/api/sms/operations/',{headers:{Authorization:`Bearer ${env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN}`}});
const dash=await (await handleSmsOperations(req,{env,store,now})).json();
check('dashboard loads',dash.ok&&dash.conversations.length===1&&dash.counts.link_delivered===1&&dash.retries.length===1&&dash.health.successCount===1);
check('campaign report',dash.campaigns[0].key==='jm'&&dash.campaigns[0].total===1);
check('masked phone',dash.conversations[0].contact.includes('•••')&&!dash.conversations[0].contact.includes('5551212'));
const handoffStore=new Store();const convo={id:cid,state:'coveragefit_ready',intent:'buyer',answers:{propertyAddress:'123 Main Street'},attribution:null};const hand=await createSmsHandoff(convo,{store:handoffStore,operationsStore:store,now,origin:'https://coveragefit.com'});await store.setJSON(`sms-live-conversations/${cid}`,{...convo,state:'awaiting_producer',handoff:{url:hand.url},contactPhone:'+14085551212',createdAt:now.toISOString(),updatedAt:now.toISOString()});
const hreq=new Request('https://coveragefit.com/api/sms/handoff/read',{method:'POST',headers:{Origin:'https://coveragefit.com','Content-Type':'application/json'},body:JSON.stringify({token:hand.token})});const hres=await handleSmsHandoffRead(hreq,{store:handoffStore,operationsStore:store,now});const hd=await hres.json();
check('handoff keeps conversation identifier private',hd.ok&&!Object.prototype.hasOwnProperty.call(hd.handoff,'conversationId')&&/^sot_/.test(hd.handoff.operationsRef));
check('handoff marks started',(await store.get(`sms-live-conversations/${cid}`)).coverageFitStartedAt===now.toISOString());
const reportStore=new Store();const report={assessment:'home',score:88,consumer:{name:'Test Buyer',email:'test@example.com'},integration:{operationsRef:hd.handoff.operationsRef},assessmentCompletion:{scoreIsFinal:true,missingRequiredCount:0}};const preq=new Request('https://coveragefit.com/api/reports/create',{method:'POST',headers:{Origin:'https://coveragefit.com','Content-Type':'application/json'},body:JSON.stringify({report})});const pres=await handleProspectReportCreate(preq,{store:reportStore,operationsStore:store,now});check('report create',pres.status===201);check('report marks completed',(await store.get(`sms-live-conversations/${cid}`)).coverageFitCompletedAt===now.toISOString());
check('docs',fs.existsSync('SPRINT-RC-SMS-1.9.md')&&fs.readFileSync('CHANGELOG.md','utf8').includes('Operations Dashboard + Reliability'));
console.log(JSON.stringify({sprint:'RC-SMS-1.9',passed:checks.length,failed:0,checks},null,2));
