import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {cleanDisplacementContext} from '../../server/pvx-displacement-core.mjs';
import {buildDataManagerConversion} from '../../server/displacement-conversion-core.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));const tests=[];function t(n,ok,e=''){tests.push({acceptance:n,pass:Boolean(ok),evidence:e});}
const generic=read('nonrenewal/index.html'),safeco=read('nonrenewal/safeco/index.html'),intake=read('assets/js/displacement-intake.js'),ctx=read('assets/js/displacement-context.js'),attr=read('assets/js/attribution.js'),checkpoint=read('server/pvx-checkpoint-core.mjs'),unified=read('server/pvx-unified-producer-record-core.mjs'),brief=read('server/pvx-producer-brief-core.mjs'),workspace=read('assets/js/agent-workspace.js'),queue=read('server/pvx-producer-action-queue-core.mjs'),css=read('assets/css/displacement.css'),events=read('server/pvx-event-core.mjs'),normalized=JSON.parse(read('cf-disp/baseline/NORMALIZED_REGRESSION.json'));
const actual=cleanDisplacementContext({eventType:'nonrenewal_notice',carrier:'safeco',timingBucket:'within_30',propertyType:'condo',postalCode:'95118'},new Date('2026-08-24T14:00:00-07:00'));const future=cleanDisplacementContext({eventType:'nonrenewal_notice',carrier:'safeco',timingBucket:'over_90',propertyType:'condo',postalCode:'95118'},new Date('2026-08-24T14:00:00-07:00'));
t('1 direct generic nonrenewal entry',exists('nonrenewal/index.html')&&generic.includes('data-displacement-intake'),'route');
t('2 Safeco paid-search-style entry',exists('nonrenewal/safeco/index.html')&&attr.includes('gclid')&&safeco.includes('data-default-carrier="safeco"'),'route + click attribution');
t('3 Safeco organic entry',safeco.includes('rel="canonical" href="https://coveragefit.com/nonrenewal/safeco/"')&&safeco.includes('Primary factual sources'),'canonical + useful content');
t('4 unknown carrier entry',read('assets/js/displacement-carriers.js').includes("other")&&read('assets/js/displacement-carriers.js').includes("unsure"),'carrier registry');
t('5 actual nonrenewal',actual.eventType==='nonrenewal_notice'&&actual.noticeReceived===true,'context runtime');
t('6 cancellation',cleanDisplacementContext({eventType:'cancellation_notice'}).noticeReceived===true,'context runtime');
t('7 anticipatory concern',cleanDisplacementContext({eventType:'concerned_may_not_renew'}).customerCertainty==='anticipated','context runtime');
t('8 comparison-only visitor',cleanDisplacementContext({eventType:'comparison_only'}).customerCertainty==='comparison','context runtime');
t('9 short-deadline customer',actual.operationalUrgency==='immediate','runtime urgency');
t('10 future-deadline customer',future.operationalUrgency==='early','runtime urgency');
t('11 value before contact',generic.indexOf('dispResultBody')<generic.indexOf('dispContactTitle'),'DOM order');
t('12 no-contact self-service',generic.includes('id="dispContinuePvx"')&&generic.includes('Continue my review'),'self-service CTA');
t('13 explicit contact request',intake.includes("contactConsent!=='on'")&&generic.includes('Ask someone to contact me'),'explicit checkbox + CTA');
t('14 channel-specific consent',intake.includes("sms:preferred==='text'&&data.channelConsent==='on'")&&intake.includes("call:preferred==='call'&&data.channelConsent==='on'")&&intake.includes("email:preferred==='email'&&data.channelConsent==='on'"),'channel consent runtime');
t('15 zero-repeat PVX continuation',ctx.includes('prefilledQuestionIds')&&ctx.includes("'shoppingReason'")&&ctx.includes('exactCustomerWords'),'PVX prefill');
t('16 Snapshot persistence',checkpoint.includes('displacementContext')&&checkpoint.includes('cleanDisplacementContext'),'checkpoint storage');
t('17 continue later/resume',exists('server/pvx-resume-core.mjs')&&exists('pvx/continue/index.html'),'inherited secure resume surfaces preserved');
t('18 Home Profile continuation',ctx.includes('displacementContext:r')&&exists('pvx/home-profile/index.html'),'profile hydration + route');
t('19 Policy Review continuation',exists('pvx/policy/index.html')&&ctx.includes('reviewContext'),'existing PVX policy route + review context');
t('20 producer record',unified.includes('displacementContext'),'unified record');
t('21 Workspace displacement context',workspace.includes('displacementContext')&&read('agent/workspace/index.html').includes('Carrier displacement'),'workspace');
t('22 follow-up',queue.includes('notificationEligible')&&queue.includes('explicitContactRequest'),'existing queue');
t('23 acquisition attribution',['gclid','gbraid','wbraid','gclsrc'].every(x=>attr.includes(x)),'first/session attribution');
const conversion=await buildDataManagerConversion({record:{checkpointId:'pvxc_E2E',contact:{email:'test@example.com',mobile:'4085551212'},attribution:{gclid:'E2E-GCLID'},consent:{contact:true}},eventName:'policy_bound',occurredAt:'2026-08-24T14:00:00-07:00'});t('24 Google conversion-state creation',conversion.row['Conversion action']==='Policy Bound'&&conversion.row.GCLID==='E2E-GCLID','Data Manager adapter runtime');
t('25 SEO indexability',read('sitemap.xml').includes('/nonrenewal/safeco/')&&generic.includes('meta name="description"')&&safeco.includes('rel="canonical"'),'sitemap/meta/canonical');
t('26 mobile/accessibility',css.includes('@media(max-width:360px)')&&css.includes('prefers-reduced-motion')&&generic.includes('aria-live="polite"')&&generic.includes('Skip to content'),'source certification');
t('27 privacy/security',actual.semanticBoundary.contactPermission===false&&conversion.privacy.generalAnalyticsContainsPii===false&&read('server/pvx-displacement-core.mjs').includes("/^\\d{5}$/"),'semantic + analytics guardrails');
t('28 protected-hash comparison',exists('CF_DISP_PROTECTED_HASH_COMPARISON.md')||exists('cf-disp/baseline/PROTECTED_HASHES_FINAL.sha256'),'hash evidence');
t('29 normalized legacy regression',normalized.zeroUnexplainedNewFailures===true&&normalized.final.failed===97,'normalized regression');
t('30 rollback capability',exists('CF_DISP_ROLLBACK_RUNBOOK.md')||exists('cf-disp/releases/CF_DISP_5_2_ROLLBACK.md'),'rollback artifact');
const failed=tests.filter(x=>!x.pass);console.log(JSON.stringify({suite:'CF-DISP final acceptance E2E',tests:tests.length,passed:tests.length-failed.length,failed:failed.length,results:tests},null,2));if(failed.length)process.exit(1);
